name: Lable Issues
on:
  issues:
    types:
      - opened

jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add a label
        env: 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          issue_tile="${{github.event.issue.title}}"
          if [["$issue_title" == *"bug"*]]; then
            echo "Issue is about a bug!"
          else
            echo "Not a bug"
          fi