name: node app workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
env: # these are setup at the environment in the runner
  MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }} # access repository level variables
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }} # access repository level secrets
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    name: unit-testing
    steps:
      - name: Repository Checkout # download repo
        uses: actions/checkout@v4 
      - name: Setup Node
        uses: actions/setup-node@v4 # install node
        with:
          node-version: 18
      - name: Install dependencies # install dependecies
        run: npm instal
      - name: Run Tests # run the unit tests
        run: npm test
      - name: Archive test result
        uses: actions/upload-artifact@v3
        with:
          name: Mocha-Test-Result
          path: test-results.xml
      
