name: node app workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
env: # these are setup at the environment in the runner
  MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }} # access repository level variables
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }} # access repository level secrets
jobs:
  unit-testing:
    strategy:
      matrix:
        nodejs_version: [18,19,20]
        operating_system: [ubuntu-latest, macos-latest]
        exclude:
          - nodejs_version: 18
            operating_system: macos-latest
    runs-on: ${{ matrix.operating_system }}
    name: unit-testing
    steps:
      - name: Repository Checkout # download repo
        uses: actions/checkout@v4 
      - name: Setup Node
        uses: actions/setup-node@v4 # install node
        with:
          node-version: ${{ matrix.nodejs_version }}
      - name: Install dependencies # install dependecies
        run: npm install
      - name: Run Tests # run the unit tests
        run: npm test
      - name: Clean up old artifacts
        run: |
          rm -rf test-results.xml
      - name: Archive test result
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-Test-Result # name of the downloaded file. name.zip 
          path: test-results.xml # where the file is present on the runner vm
      
